# config/config.yaml

embedding:
  model_name: "BAAI/bge-m3"

chroma:
  persist_directory: "C:/AI-research-agent/VectorDatabase"
  collection_name: "QA_papers"

retrieval:
  top_k: 5

chunking:
  chunk_size: 800
  overlap: 100

llm:
  provider: "groq"
  model_name: "llama-3.3-70b-versatile"
  temperature: 0.3

logging:
  filename: "processing_log.log"
  level: "INFO"

pdf_processor:
  pdf_path: 'C:/AI-research-agent/Data/pdf'
  output_folder : 'C:/AI-research-agent/Data/markdown'